import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=path.dirname(fileURLToPath(import.meta.url)),publicDir=path.resolve(root,'../../demo/site/inteligencia-geografica/dados');
const data=JSON.parse(await fs.readFile(path.join(publicDir,'estica.json'),'utf8'));
const cities=JSON.parse(await fs.readFile(path.join(publicDir,'municipios.json'),'utf8')).cities.sort((a,b)=>a.uf.localeCompare(b.uf)||a.name.localeCompare(b.name,'pt-BR'));
const index=new Map(data.cities.map(c=>[c.id,c])),wb=Workbook.create();
for(const [name,mode] of [['Principal','primary'],['Principal ou secundaria','any']]){
 const s=wb.worksheets.add(name);s.showGridLines=false;
 s.getRange('A1').values=[['Estica: concorrência potencial por cidade']];s.getRange('A2').values=[['Receita Federal, setembro/2026. Pilates identificado pelo nome é subconjunto dos CNAEs. Não somar.']];
 const head=['Código IBGE','Município','UF','População 2026','Academias e condicionamento','Fisioterapia (relacionada)','União dos dois CNAEs','Pilates no nome (subconjunto)','Pilates por 10 mil habitantes','Referência','Fonte'];
 const rows=cities.map(c=>{const r=index.get(c.id);return [c.id,c.name,c.uf,c.metrics.population?.value??null,...r[mode],r[mode==='primary'?'totalPrimary':'totalAny'],r[mode==='primary'?'pilatesPrimary':'pilatesAny'],null,'2026-09',data.source];});
 const end=rows.length+4;s.getRange(`A4:K${end}`).values=[head,...rows];s.getRange(`A1:K${end}`).format.font={name:'Arial',size:10,color:'#111516'};
 s.getRange('A1').format.font={name:'Arial',size:17,bold:true,color:'#111516'};s.getRange('A1').format.rowHeight=28;s.getRange('A2').format.rowHeight=24;
 s.getRange(`A4:K${end}`).format.columnWidth=21;s.getRange('A4:K4').format={fill:'#111516',font:{name:'Arial',size:10,bold:true,color:'#ffffff'},rowHeight:62,wrapText:true,verticalAlignment:'center'};
 s.getRange(`A5:K${end}`).format.rowHeight=21;s.getRange(`A5:A${end}`).setNumberFormat('@');s.getRange(`D5:H${end}`).setNumberFormat('#,##0');s.getRange(`I5:I${end}`).setNumberFormat('#,##0.0');s.getRange(`B4:B${end}`).format.columnWidth=30;s.getRange(`C4:C${end}`).format.columnWidth=7;s.getRange(`K4:K${end}`).format.columnWidth=65;
 s.getRange('I5').formulas=[['=IF(AND(ISNUMBER(D5),D5>0,ISNUMBER(H5)),H5/D5*10000,"")']];s.getRange(`I5:I${end}`).fillDown();s.freezePanes.freezeRows(4);s.freezePanes.freezeColumns(3);const t=s.tables.add(`A4:K${end}`,true,mode==='primary'?'EsticaPrincipal':'EsticaQualquerAtividade');t.style='TableStyleLight1';t.showBandedRows=false;
 const img=await wb.render({sheetName:name,range:'A1:I10',scale:1,format:'png'});await fs.writeFile(path.join(root,'../qa/estica-planilha-'+mode+'.png'),new Uint8Array(await img.arrayBuffer()));
}
const s=wb.worksheets.add('Fontes e metodo');s.showGridLines=false;
const rows=[['Estica: fontes e método',''],['Universo','CNPJs ativos com CNAE 9313100 ou 8650004. Filiais contam separadamente.'],['Condicionamento físico','CNAE 9313100: academias, musculação, yoga, Pilates, alongamento, funcional e instrutores individuais. Não equivale somente a espaços físicos.'],['Fisioterapia','CNAE 8650004: atividade relacionada, não confirma Pilates ou concorrência direta.'],['Pilates identificado','Palavra inteira PILATES, ignorando caixa e acentos, no nome fantasia ou na razão social. Exige um dos dois CNAEs selecionados.'],['Cobertura de Pilates','Parcial. Nomes podem omitir a modalidade. Razão social vale para a empresa e não confirma oferta em cada filial.'],['Não somar','Pilates já faz parte dos dois grupos de CNAE. Na aba de secundárias, os próprios grupos também podem se sobrepor.'],['Atividade principal','Filtra CNAE principal selecionado. Pilates nesta aba é nome mais principal 9313100 ou 8650004.'],['Concorrência potencial','Cadastro não confirma funcionamento, ponto aberto, público, serviço atual ou concorrência direta da Estica.'],['Localização','Totais municipais. Não há geocodificação de endereço ou coordenadas individuais.'],['Referência','Setembro/2026, arquivos gerados em 13/09. Sem atualização automática.'],['População','Estimativa IBGE 2026. Taxa descritiva, não mede saturação.'],['Dados CNPJ',data.source],['CNAE condicionamento','https://cnae.ibge.gov.br/?view=subclasse&tipo=cnae&versao=10.1.0&subclasse=9313100'],['CNAE fisioterapia','https://cnae.ibge.gov.br/?view=subclasse&tipo=cnae&versao=10.1.0&subclasse=8650004'],['Layout','https://www.gov.br/receitafederal/dados/cnpj-metadados.pdf'],['Municípios','https://www.gov.br/receitafederal/dados/municipios.csv'],['População IBGE','https://sidra.ibge.gov.br/tabela/6579']];
s.getRange(`A1:B${rows.length}`).values=rows;s.getRange(`A1:B${rows.length}`).format={font:{name:'Arial',size:11,color:'#111516'},wrapText:true,rowHeight:48,verticalAlignment:'center'};s.getRange(`A1:A${rows.length}`).format.columnWidth=40;s.getRange(`B1:B${rows.length}`).format.columnWidth=100;s.getRange('A1').format.font={name:'Arial',size:17,bold:true,color:'#111516'};
const img=await wb.render({sheetName:'Fontes e metodo',range:'A1:B18',scale:1,format:'png'});await fs.writeFile(path.join(root,'../qa/estica-planilha-fontes.png'),new Uint8Array(await img.arrayBuffer()));
console.log((await wb.inspect({kind:'table',range:'Principal!A4:I7',include:'values,formulas',tableMaxRows:4,tableMaxCols:9,maxChars:1500})).ndjson);
console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:20},maxChars:500})).ndjson);
const output=path.join(root,'work/estica-municipios.xlsx');const xlsx=await SpreadsheetFile.exportXlsx(wb);await xlsx.save(output);await fs.copyFile(output,path.join(publicDir,'estica-municipios.xlsx'));console.log('Excel Estica exportado.');
