'use strict';
const fs=require('fs'),path=require('path'),E=require('../../../demo/site/inteligencia-geografica/competitiveness.js');
const dir=path.resolve(__dirname,'../../../demo/site/inteligencia-geografica/dados');
const d=JSON.parse(fs.readFileSync(path.join(dir,'competitividade.json'))),g=new Map(JSON.parse(fs.readFileSync(path.join(dir,'municipios.json'))).cities.map(r=>[r.id,r]));
const rows=d.cities.map(r=>({...r,name:g.get(r.id).name,uf:g.get(r.id).uf})),n=x=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(x);
let md='# Leitura dos índices de competitividade\n\nStatus: Revisão. Fotografia de 27/09/2026, versão `competitividade-v1`. Hipóteses para orientar pesquisa, sem recomendação de abertura. Não aplica disponibilidade territorial: as tabelas abaixo usam apenas dados públicos e incluem cidades com presença da rede. Na plataforma, o filtro Sem registro restringe a marca escolhida.\n\n';
const evidence={version:d.version,brands:{}};
for(const b of ['agrobar','estica']){
 const base=E.ranked(rows,b,d.defaults[b]),scenario=b==='agrobar'?{competition:40,fit:25,market:35,economy:0}:{competition:35,fit:20,market:45,economy:0},changed=E.ranked(rows,b,scenario);
 md+='## '+(b==='agrobar'?'Agrobar':'Estica')+'\n\n';
 const cuts=[['Brasil',r=>true],['50 a 500 mil habitantes',r=>r.population>=50000&&r.population<=500000],['Paraná, 50 a 500 mil habitantes',r=>r.uf==='PR'&&r.population>=50000&&r.population<=500000],['50 a 500 mil e renda mediana a partir de R$ 1.000',r=>r.population>=50000&&r.population<=500000&&r.income>=1000]];
 evidence.brands[b]={cuts:[],scenario};
 for(const [title,match] of cuts){
  const r=base.filter(x=>match(x)&&x.score!==null),c=changed.filter(x=>match(x)&&x.score!==null),top=new Set(r.slice(0,20).map(x=>x.id)),overlap=c.slice(0,20).filter(x=>top.has(x.id)).length;
  evidence.brands[b].cuts.push({title,count:r.length,overlapTop20:overlap,top5:r.slice(0,5).map(x=>({id:x.id,name:x.name,uf:x.uf,score:x.score}))});
  md+='### '+title+'\n\n'+n(r.length)+' cidades com nota completa.\n\n| Cidade | Nota base | População 2026 | Renda mediana R$/pessoa/mês 2022 | Menor pressão 0–100 |\n|---|---:|---:|---:|---:|\n'+r.slice(0,5).map(x=>`| ${x.name} / ${x.uf} | ${n(x.score)} | ${n(x.population)} | ${n(x.income)} | ${n(x[b].competition)} |`).join('\n')+'\n\n';
  md+=`Sensibilidade: ao dar mais peso a escala/renda (${scenario.competition}% concorrência, ${scenario.fit}% ${b==='agrobar'?'afinidade agro':'densidade'}, ${scenario.market}% escala/renda), ${overlap} das ${Math.min(20,r.length)} primeiras cidades continuam entre as 20 primeiras. A mudança é de hipótese; não comprova que um ranking é melhor.\n\n`;
 }
 const low=base.filter(r=>r.score>=70&&r.population<25000).length;
 md+=`Há ${n(low)} cidades abaixo de 25 mil habitantes com nota base a partir de 70. Esse é um recorte obrigatório de checagem de escala, não uma lista automática de oportunidades.\n\n`;
 const london=base.find(r=>r.id==='4113700'),nova=base.find(r=>r.id==='4117107');
 md+=`Londrina recebe ${n(london.score)}; Nova Londrina, ${n(nova.score)}. São municípios distintos. Uma busca por “Londrina” retorna ambos; compare população, renda e concorrência antes de interpretar a ordem.\n\n`;
}
md+='## Como usar na reunião\n\n1. Escolher a marca e o recorte de população; aplicar Sem registro se a pergunta for expansão em novas cidades.\n2. Abrir a matriz e separar menor pressão com escala/renda de menor pressão com escala insuficiente. O corte 50 é exploratório, não limiar de viabilidade.\n3. Comparar quatro cidades, incluindo uma referência conhecida. Conferir componentes, valores absolutos, grupo de pares e datas.\n4. Mudar os pesos, observar nota e posição nacional e salvar a hipótese. Alta sensibilidade significa que a escolha depende fortemente dos critérios.\n5. Exportar CSV ou relatório da seleção para a reunião; validar concorrentes reais, imóveis, demanda, território e resultados das unidades antes da decisão.\n\n## Achados e decisões pendentes\n\n- O Agrobar favorece municípios com pouca concorrência cadastrada e agro relevante; isso pode colocar cidades de renda baixa no topo. O recorte adicional de renda permite examinar esse efeito sem alterar a fórmula histórica.\n- A proposta Estica favorece concentração urbana e menor oferta cadastral proporcional. Municípios metropolitanos podem compartilhar demanda e concorrência com vizinhos, algo que o índice municipal não modela.\n- Pilates no nome tem cobertura parcial; academias inclui instrutores. Os percentis combinam dois sinais que podem se sobrepor. Não equivalem a concorrentes únicos nem a capacidade instalada.\n- PIB total está desligado por padrão. É útil para leitura econômica, mas pode repetir o efeito de população e não substitui renda disponível. A composição VAB é de 2021; o PIB é de 2023.\n- Faltam séries de faturamento, margem, investimento, sobrevivência e capacidade por unidade para calibrar pesos. Presença da marca ou status operando não é evidência de rentabilidade.\n- Próxima decisão humana: validar os pesos Estica e quais cortes mínimos de população/renda devem representar cada formato. Os presets atuais são hipóteses explícitas, editáveis.\n\n## Reprodução e fontes\n\n`node 05-dashboard/inteligencia-geografica/analises/competitividade/analisar.cjs` gera este documento e a evidência JSON. O gerador de componentes e os hashes de entrada estão em `gerar.py` e `auditoria.json`. Fontes e método detalhados no [README](README.md).\n';
fs.writeFileSync(path.join(__dirname,'ANALISE.md'),md);fs.writeFileSync(path.join(__dirname,'analises.json'),JSON.stringify(evidence,null,2)+'\n');console.log('Análise e recortes gerados.');
